DEFAULT_AUTHOR = 'Maximilian Keßler'

LICENSE = [
    'Copyright © {year} {copyright_holders}',
    '',
    'Permission is hereby granted, free of charge, to any person obtaining a copy',
    'of this software and associated documentation files (the “Software”), to deal',
    'in the Software without restriction, including without limitation the rights',
    'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
    'copies of the Software, and to permit persons to whom the Software is',
    'furnished to do so, subject to the following conditions:',
    'The above copyright notice and this permission notice shall be included in all',
    'copies or substantial portions of the Software.',
    '',
    'THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
    'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
    'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
    'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
    'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,',
    'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE',
    'SOFTWARE.'
]

PACKAGE_INFO_TEXT = [
    "This LaTeX package is free software and distributed under the MIT License. You",
    "may use it freely for your purposes. The latest version of the package can be",
    "obtained via GitHub under",
    "   https://github.com/kesslermaximilian/LatexPackages",
    "For further information see the url above.",
    "Reportings of bugs, suggestions and improvements are welcome, see the README",
    "at the Git repository for further information."
]

PYTEX_INFO_TEXT = [
    "This package has been generated by PyTeX, available at",
    "   https://github.com/kesslermaximilian/PyTeX",
    "and built from source file '{source_file}'.",
    "It is STRONGLY DISCOURAGED to edit this source file directly, since local changes",
    "will not be versioned by Git and overwritten by the next build. Always edit the",
    "source file and build the package again."
]
